version: '3'

app-web:  
  build: .
  ports:
    - "8081:8080"
  links:
    - app-db

app-db:  
  build: ./postgresql
  expose:
    - "5432"
  volumes_from:
    - app-db-data

app-db-data:  
  image: edm/data
  command: echo 'Data Container for PostgreSQL'
  volumes:
    - /var/lib/postgresql/data